### ISSUE TITLE
AI is beatable

### ISSUE THREAD

**Issue by mbrichman** [orlando-paredes-hamsho/tic-tac-toe#1]
Hello Orlando. Thank you for your submission. Unfortunately during testing of the game, I am able to beat your AI (on the first try). Please resolve this. I would like to see two additional commits to your code:

1.  a commit with a failing test(s) exposing your bug
2. a commit with the fix

**Comment by orlando-paredes-hamsho** [comment]
Thank you very much Mark! I am in fact having difficulties in deciding what to do when a move is not immediatly beneficial to the AI.

I'm on my way to the airport right now, but I will try to submit both commits either tonight or early tomorrow, and comment on this thread when I do. Or maybe at the airport if I have an internet conection there (mexico airports huh?)

Once again thank you for finding the bug, and reviewing my submission!

**Comment by mbrichman** [comment]
Please take the time you need to ensure it's working. I look forward to seeing the update.

-Mark

**Comment by orlando-paredes-hamsho** [comment]
Internet was decent enough for me to push the fixes, but not too much.

Gotta tell you, this was surprisingly fun, I fixed it and tried to find more but the AI just wouldn't let me win. I like it.

Anyway, thanks for the patience! Let me know what you think!

EDIT: Adding link to master (it has all the changes, I forgot to link to the issue tho -_-)
https://github.com/orlando-paredes-hamsho/tic-tac-toe

**Comment by mbrichman** [comment]
This looks good. I appreciate the fix, and also your responsiveness in getting this back. Your tests address the logic flaws. We will be in touch shortly to talk about next steps.
